# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aogaki/DAQ/WebApiELIADE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aogaki/DAQ/WebApiELIADE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aogaki/DAQ/WebApiELIADE/CMakeFiles /home/aogaki/DAQ/WebApiELIADE//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aogaki/DAQ/WebApiELIADE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named eliade-api-test

# Build rule for target.
eliade-api-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 eliade-api-test
.PHONY : eliade-api-test

# fast build rule for target.
eliade-api-test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eliade-api-test.dir/build.make CMakeFiles/eliade-api-test.dir/build
.PHONY : eliade-api-test/fast

#=============================================================================
# Target rules for targets named eliade-api

# Build rule for target.
eliade-api: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 eliade-api
.PHONY : eliade-api

# fast build rule for target.
eliade-api/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eliade-api.dir/build.make CMakeFiles/eliade-api.dir/build
.PHONY : eliade-api/fast

#=============================================================================
# Target rules for targets named eliade-api-lib

# Build rule for target.
eliade-api-lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 eliade-api-lib
.PHONY : eliade-api-lib

# fast build rule for target.
eliade-api-lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eliade-api-lib.dir/build.make CMakeFiles/eliade-api-lib.dir/build
.PHONY : eliade-api-lib/fast

src/App.o: src/App.cpp.o
.PHONY : src/App.o

# target to build an object file
src/App.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eliade-api.dir/build.make CMakeFiles/eliade-api.dir/src/App.cpp.o
.PHONY : src/App.cpp.o

src/App.i: src/App.cpp.i
.PHONY : src/App.i

# target to preprocess a source file
src/App.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eliade-api.dir/build.make CMakeFiles/eliade-api.dir/src/App.cpp.i
.PHONY : src/App.cpp.i

src/App.s: src/App.cpp.s
.PHONY : src/App.s

# target to generate assembly for a file
src/App.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eliade-api.dir/build.make CMakeFiles/eliade-api.dir/src/App.cpp.s
.PHONY : src/App.cpp.s

src/db/Database.o: src/db/Database.cpp.o
.PHONY : src/db/Database.o

# target to build an object file
src/db/Database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eliade-api-lib.dir/build.make CMakeFiles/eliade-api-lib.dir/src/db/Database.cpp.o
.PHONY : src/db/Database.cpp.o

src/db/Database.i: src/db/Database.cpp.i
.PHONY : src/db/Database.i

# target to preprocess a source file
src/db/Database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eliade-api-lib.dir/build.make CMakeFiles/eliade-api-lib.dir/src/db/Database.cpp.i
.PHONY : src/db/Database.cpp.i

src/db/Database.s: src/db/Database.cpp.s
.PHONY : src/db/Database.s

# target to generate assembly for a file
src/db/Database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eliade-api-lib.dir/build.make CMakeFiles/eliade-api-lib.dir/src/db/Database.cpp.s
.PHONY : src/db/Database.cpp.s

test/tests.o: test/tests.cpp.o
.PHONY : test/tests.o

# target to build an object file
test/tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eliade-api-test.dir/build.make CMakeFiles/eliade-api-test.dir/test/tests.cpp.o
.PHONY : test/tests.cpp.o

test/tests.i: test/tests.cpp.i
.PHONY : test/tests.i

# target to preprocess a source file
test/tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eliade-api-test.dir/build.make CMakeFiles/eliade-api-test.dir/test/tests.cpp.i
.PHONY : test/tests.cpp.i

test/tests.s: test/tests.cpp.s
.PHONY : test/tests.s

# target to generate assembly for a file
test/tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eliade-api-test.dir/build.make CMakeFiles/eliade-api-test.dir/test/tests.cpp.s
.PHONY : test/tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... eliade-api"
	@echo "... eliade-api-lib"
	@echo "... eliade-api-test"
	@echo "... src/App.o"
	@echo "... src/App.i"
	@echo "... src/App.s"
	@echo "... src/db/Database.o"
	@echo "... src/db/Database.i"
	@echo "... src/db/Database.s"
	@echo "... test/tests.o"
	@echo "... test/tests.i"
	@echo "... test/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

